### ISSUE TITLE
\@textsuperscript in doc leading to problems

### ISSUE THREAD

**Issue by Hypercube1234** [gusbrs/postnotes#6]
In the documentation, the line containing \@textsuperscript leads to problems when reproducing (the »@«)

https://github.com/gusbrs/postnotes/blob/10ba78acb5e3dfff3729577ec97cb7696bfab34c/postnotes-doc.tex#L382

Looks like it was predefined from »listings«. I noticed this when I played around with the font-formatting of the label.

**Comment by gusbrs** [comment]
What I see in the manual's PDF is:

![Screenshot from 2024-05-30 20-07-29](https://github.com/gusbrs/postnotes/assets/19410606/56b039fa-4b5b-4d7c-82b3-7f3464c4bd45)

which looks correct to me. Could you elaborate what do you mean by "problems"?

**Comment by Hypercube1234** [comment]
Copying the default-values from the documentation into the preamble leads to an incorrect display of the footnote-marker. Removing the @ corrects the display, however.

`\documentclass{book}`

`\usepackage{fontspec}`
`\usepackage{hyperref}`
`\usepackage{postnotes}`
`\postnotesetup{`
`  makemark = {#2\hbox{\@textsuperscript{\normalfont#1}}#3} ,`
`  maketextmark = {#2#1.#3}}`

`\begin{document}`

`Test\postnote{Test}`
`\printpostnotes`

`\end{document}`

![github_postnotes](https://github.com/gusbrs/postnotes/assets/79299877/5782d630-a73a-4113-9838-86145f73f7b4)

**Comment by gusbrs** [comment]
Ah, I see. But that is a problem in your document, not in the manual. If you want to use a macro containing a `@` you'd need to wrap it between `\makeatletter` and `\makeatother`, like so:

```tex
\documentclass{book}

\usepackage{fontspec}
\usepackage{hyperref}
\usepackage{postnotes}
\makeatletter
\postnotesetup{
  makemark = {#2\hbox{\@textsuperscript{\normalfont#1}}#3} ,
  maketextmark = {#2#1.#3}}
\makeatother

\begin{document}

Test\postnote{Test}
\printpostnotes

\end{document}
```

The manual is making a statement on the default value of the option, which is indeed `{#2\hbox{\@textsuperscript{\normalfont#1}}#3}`, but the handling of catcodes for macros containing `@` is already done in the package (inside the `.sty`). This value is so because it is the same definition used in the kernel for footnotes, which uses the internal `\@textsuperscript`.

But in your document you can very well just go with `\textsuperscript` and not bother with that. That's OK. 

Anyway, thanks for the concern and the report.
